sentence=input("enter the sentence u want ")
seperator=input("enter the separator u want ")
sentence=sentence.replace(", ", "")
sentence=sentence.replace("!","")
sentence=sentence.replace(".","")
sentence=sentence.replace("?","")
words=sentence.split()
words.sort(reverse=True)
result=seperator.join(words)
print("the sorted sentence is ",result)