decimal=int(input(" Enter a decimal number: "))
binary=bin(decimal).replace("0b","")
octal=oct(decimal).replace("0o","")
hexadecimal=hex(decimal).replace("0x","").upper()
# print(f"Decimal: {decimal}")
print(f"Binary: {binary}")
print(f"Octal: {octal}")
print(f"Hexadecimal: {hexadecimal}")
print(f"binary digit length:{len(binary)}")
print(f"octal digit length:{len(octal)}")
print(f"hexadecimal digit length:{len(hexadecimal)}")
binary_decimal=int(binary,2)
octal_decimal=int(octal,8)
hexadecimal_decimal=int(hexadecimal,16)
print(f"binary to decimal:{binary_decimal}")
print(f"octal to decimal:{octal_decimal}")
print(f"hexadecimal to decimal:{hexadecimal_decimal}")